name: Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro
        run: pnpm run build
        env:
          PUBLIC_GITHUB_URL: ${{ vars.PUBLIC_GITHUB_URL }}
          PUBLIC_HCAPTCHA_SITEKEY: ${{ vars.PUBLIC_HCAPTCHA_SITEKEY }}
          HCAPTCHA_SECRET_KEY: ${{ secrets.HCAPTCHA_SECRET_KEY }}
          ADMIN_ETH_ADDRESSES: ${{ secrets.ADMIN_ETH_ADDRESSES }}
          JWT_KEY: ${{ secrets.JWT_KEY }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ex-graph
          entrypoint: server/entry.mjs
          root: dist
